DEFAULT_SEED = {
    "OpenAI": ["OpenAI, Inc.", "Open AI", "OpenAI Inc"],
    "Google": ["Google LLC", "Google, Inc.", "Alphabet Google"],
    "Microsoft": ["Microsoft Corporation", "Microsoft Corp.", "Microsoft, Inc."],
    "Meta": ["Meta Platforms", "Meta Platforms, Inc.", "Facebook AI", "Facebook"],
    "Anthropic": ["Anthropic PBC", "Anthropic AI", "Anthropic, Inc."],
    "NVIDIA": ["NVIDIA Corporation", "Nvidia", "NVIDIA Corp."],
    "Amazon": ["Amazon Web Services", "AWS", "Amazon.com, Inc."],
    "DeepMind": ["Google DeepMind", "DeepMind Technologies", "DeepMind AI"],

    "Apple": ["Apple Inc.", "Apple Computer"],
    "IBM": ["IBM Corporation", "International Business Machines"],
    "Intel": ["Intel Corporation", "Intel Corp."],
    "AMD": ["Advanced Micro Devices", "AMD Inc.", "AMD Corporation"],
    "Qualcomm": ["Qualcomm Incorporated", "Qualcomm Inc."],
    "Oracle": ["Oracle Corporation", "Oracle Corp."],
    "Cisco": ["Cisco Systems", "Cisco Systems, Inc."],
    "Salesforce": ["Salesforce.com", "Salesforce Inc."],
    "Adobe": ["Adobe Systems", "Adobe Inc."],
    "SAP": ["SAP SE", "SAP AG"],
    "Dell": ["Dell Technologies", "Dell Inc."],
    "Hewlett Packard Enterprise": ["HPE", "Hewlett-Packard Enterprise"],
    "Lenovo": ["Lenovo Group", "Lenovo Group Limited"],
    "Samsung": ["Samsung Electronics", "Samsung Electronics Co."],
    "ByteDance": ["ByteDance Ltd.", "ByteDance Limited"],
    "Alibaba": ["Alibaba Group", "Alibaba Group Holding"],
    "Baidu": ["Baidu Inc.", "Baidu, Inc."],
    "Tencent": ["Tencent Holdings", "Tencent Holdings Limited"],

    "Mistral AI": ["Mistral", "MistralAI", "Mistral AI SAS"],
    "Cohere": ["Cohere Inc.", "Cohere AI"],
    "Hugging Face": ["HuggingFace", "Hugging Face Inc.", "Hugging Face, Inc."],
    "Stability AI": ["StabilityAI", "Stability AI Ltd."],
    "xAI": ["x.ai", "X AI", "xAI Corp."],
    "Perplexity": ["Perplexity AI", "Perplexity AI, Inc."],
    "Scale AI": ["ScaleAI", "Scale AI, Inc."],
    "Databricks": ["Databricks Inc."],
    "Snowflake": ["Snowflake Inc."],
    "Palantir": ["Palantir Technologies", "Palantir Technologies Inc."],
    "Cursor": ["Cursor AI", "Anysphere", "Anysphere Inc."],
    "GitHub": ["GitHub, Inc.", "Github"],
    "GitLab": ["GitLab Inc.", "GitLab.com"],
    "Docker": ["Docker Inc.", "Docker, Inc."],
    "MongoDB": ["MongoDB Inc.", "MongoDB, Inc."],
    "Cloudflare": ["Cloudflare, Inc.", "Cloudflare Inc."],
    "Datadog": ["Datadog, Inc.", "Datadog Inc."],

    "Databricks": ["Databricks Inc.", "Databricks, Inc."],
    "Weights & Biases": ["Weights and Biases", "W&B", "Weights Biases"],
    "Perplexity": ["Perplexity AI", "Perplexity AI, Inc."],
    "Runway": ["Runway AI", "RunwayML", "Runway ML"],
    "Character.AI": ["Character AI", "Character.AI, Inc."],
    "ElevenLabs": ["Eleven Labs", "ElevenLabs Inc."],
    "Replicate": ["Replicate AI", "Replicate, Inc."],

    "Adept": ["Adept AI", "Adept Technologies", "Adept AI Labs"],
    "AI21 Labs": ["AI21", "AI21Labs", "AI21 Labs Inc."],
}
