from datetime import datetime
from typing import Any
from sqlalchemy import Boolean, DateTime, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
class Base(DeclarativeBase): pass
class RawDocument(Base):
 __tablename__='raw_documents'; id:Mapped[int]=mapped_column(Integer,primary_key=True); url:Mapped[str]=mapped_column(Text,unique=True,index=True); source_name:Mapped[str]=mapped_column(String(255),index=True); content_type:Mapped[str|None]=mapped_column(String(100)); http_status:Mapped[int|None]=mapped_column(Integer); raw_html:Mapped[str|None]=mapped_column(Text); extracted_text:Mapped[str|None]=mapped_column(Text); content_hash:Mapped[str|None]=mapped_column(String(64),index=True); discovered_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); collected_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); metadata_json:Mapped[dict[str,Any]|None]=mapped_column(JSON); processed:Mapped[bool]=mapped_column(Boolean,default=False,index=True)
class EntityRecord(Base):
 __tablename__='entity_records'; id:Mapped[int]=mapped_column(Integer,primary_key=True); record_type:Mapped[str]=mapped_column(String(50),index=True); source_name:Mapped[str]=mapped_column(String(255)); source_url:Mapped[str]=mapped_column(Text); schema_version:Mapped[str]=mapped_column(String(20),default='1.0'); canonical_name:Mapped[str|None]=mapped_column(String(500),index=True); payload:Mapped[dict[str,Any]]=mapped_column(JSON); source_content_hash:Mapped[str|None]=mapped_column(String(64)); collected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); __table_args__=(UniqueConstraint('record_type','source_url',name='uq_entity_source'),)
class EntityMapping(Base):
 __tablename__='entity_mappings'; id:Mapped[int]=mapped_column(Integer,primary_key=True); raw_name:Mapped[str]=mapped_column(String(500),index=True); normalized_name:Mapped[str]=mapped_column(String(500)); canonical_name:Mapped[str]=mapped_column(String(500),index=True); entity_type:Mapped[str]=mapped_column(String(50),index=True); match_method:Mapped[str]=mapped_column(String(100)); confidence:Mapped[float]=mapped_column(); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True))
class AcquisitionCheckpoint(Base):
 __tablename__='acquisition_checkpoints'; id:Mapped[int]=mapped_column(Integer,primary_key=True); source_name:Mapped[str]=mapped_column(String(100)); query_key:Mapped[str]=mapped_column(String(500)); next_offset:Mapped[int]=mapped_column(Integer,default=0); records_fetched:Mapped[int]=mapped_column(Integer,default=0); records_inserted:Mapped[int]=mapped_column(Integer,default=0); completed:Mapped[bool]=mapped_column(Boolean,default=False); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); __table_args__=(UniqueConstraint('source_name','query_key',name='uq_acquisition_checkpoint'),)
